apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
    namespace: pgadmin
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 17.12.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: pgadmin
    values:
        global:
            stopAll: false
        TZ: ${TIMEZONE}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_PGADMIN}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_PGADMIN}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Cluster
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            # config:
            #     volsync:
            #         - credentials: ${S3_NAME}
            #           dest:
            #             enabled: true
            #           name: config
            #           src:
            #             enabled: true
            #             trigger:
            #                 schedule: 40 0 * * *
            #           type: restic
            #           cleanupTempPVC: true
            #           cleanupCachePVC: true
        service:
            main:
                enabled: true
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                PGADMIN_DEFAULT_EMAIL: ${PROTONMAIL_USER}
                                PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}