apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:B9pu6l85bMjtKhxZ6yHD/r7T7EXdwQ==,iv:1pI2f1ChzPHVCDWTSzrDtDy/IsxCCoCSGF7IF12Kt9E=,tag:ZnEi+PFyMjwSGWxpqWLjCA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TVhDMmFpS004YXhLMjkv
            clpkWDlPSEdFOGZBWGhxS1pPa05zRXB2K2lFCk9nNnRVbGh2bnVwSGV3VnIwVFV3
            NjVJOTh1YWt1eGloT1gxU3NkY2JxaVEKLS0tIG1hSWtQSFhhZXJrSnFEUDc4UUk1
            QjY3N0lMTEk1OEp2N24xdE85SG9Ic1UKO7IUqB1RKKGnJHQreYZp2Y6JSsdNAV4R
            RUZ2N9qle54dPHLrS3Y1hAbbWXvRu+kdT45r83kgVn0L1yBCZVdsDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T19:19:55Z"
    mac: ENC[AES256_GCM,data:e+DJtaUVGQoEvN8zgtrPqI0iXtzIRMIXr5hdYyxdHg5JXp8+BBucGGvV9A75j32LWZIpGGcX2uq3Bbv7cA8ajriX2pGBGMUF9OPWcnc+bSIcX83vhqh0vu5ecgGbnpB3XHWr/U09IYkQCmOapKrY/ZUa1xvSiSuqcM9PO1zybJ8=,iv:IdXv7OMubjV/1R1Pkogkw2BxvNPa0AVZF0vWh7VrlU0=,tag:eaVmtHaF8JOEMaTm0FuZWg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
