apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:JcTjPLcfaC0JSQbcP4zoyY+4tdbC4g==,iv:hyIibVaKYxeJz0GZywIchYZtQq3twajXPwreE+JrCCs=,tag:8HgFcdtDS9C2eml7aIvVqA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNHVYenR4T3ZHYzJsNFFz
            TEFIdXZsbXhlSWNNYmpLQnhORENHL0MreVMwCmZ3SWVvZTRSRjhtL0NjU0tiVm9j
            ZktpS2tQaFo0Y01VZ2xEK3Z1RnlsZ2MKLS0tIFA2VC9xc3lkRnBNWXFNbkE1d2xF
            cWUvNTlDTWZvWE04SmRPd0k4VnVPbTgKGORCgj0UYs1j3UR/z0dKaK/euJ2nEYcn
            9oBDep5gLHzrV04oaTGCf4V5RZE7HzFmyXRWnX2cdc8WVAWLG3eYuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T18:37:52Z"
    mac: ENC[AES256_GCM,data:+IZb2l+Jm7lWWSnl3ALznhuQ/Ce8n1BFEYpThoMahaTyv1Wsk9l3n6yKzpMWRibJnQli0aRo1pbg7/nej6UP0aY1PmSLSDoy8BamsT7uM0FIqey63lpzY04BzlZJ+iUoMRMnuDLOEKjdra7lnstwZeBqnffOdW14XNBlz2+UWVo=,iv:7NLAZPfhDLJZcB8Frla2bJo3sKwrKJ9U+A3yNrnCta4=,tag:vH2a6ny7NE5Zv2WcKKzodw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
