apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:K3BhNpGFSvPnidi65WEd5Hm6AsY5ig==,iv:7n7Am5wER7jgqbUy4CwhlmGk2aJilqa4uSgvA83P8u8=,tag:HYucAOJqS8+Y8pF6Ig4btw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVFBZV3haQlE3T09icTdE
            WHdpL09mamdndnB5aG9JZC85bGJVTWQra0NNCmszUktuaTBlcU9NTlppbUpzSWIr
            TEh5aVJuY3k4R3QzOVlGcC9UYzVoYlEKLS0tIG1xT2gxdndvaUJqNS94QVlPb1Mw
            Q3RuVVhlQ0VDQm5jSGhXcDN2MHdFY0EKn9BZuyhsFEkxh8Q9qxOGo3aFqEt1G/7L
            rLK35LQaNdUmJkJxoGiURrxepUqANiBYjX5wariXRe7p0QkaVtbrMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T14:23:08Z"
    mac: ENC[AES256_GCM,data:XiU/4AtTAjyrfMZIV4v+xANPvImZwaoez8t8MOGsgol+I8dhJGNdEmrc3d/v/2WXVO97W9ERDQ59yr0is04vNp6K++WejSWo5xsnva1pqKdMeZ5O1OZpOIfjkHxnL8alzzfWlH2tn37e54Jy1ZF9tFGK5d4rPmJhckh+51oYf8o=,iv:gfut8ubAQhbeCQoYSCw4vY8ARhPUkEwLfO+8VmQH58E=,tag:xxJrf1esuYiLyNiwovMVRg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
