apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:q2S+/PENbZzAA199wnEOf8nz8LDhyw==,iv:aXMmjf9pZ548bDUhcsSHRLyagv9qDI46oIUJI9fDVow=,tag:Y0hQrxUg88lCuPkkAsEjxg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU1Fna0ZZcy81Qm15MEZ1
            NjdyN2RTVlRDYlpwMTlOMUJhcE9KSE1ocVJvCmkyYURuWGwwa29JZmhTUC9TWDVW
            U3o3WEd0cmM1R0JaR0VJeUp3aFA2S0kKLS0tIDUvSGg1bjBHUDk4Zmk4aDY3SXp5
            TjFvYVd3Qyt1TmR0am1MeEUxamZ4MEkKG3rMfvDnKn8SejaZedxmZa1iWZ40O5aG
            keR34FegND7Ug1sZV7wE84Zf6xJxyTwZ8z+MpBBQZFGe+asivJWmmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T21:10:22Z"
    mac: ENC[AES256_GCM,data:Zt5aSnreRLs91twBAIyia96Mq1j6mAtuMh2TqpBfv25gw/e6vGzpUb+TK2CFlPbIM2J8C9jHaz8DCkTorDzYKCJ8GHvzJb1K0AwrmmCdMkT4QyPItgPPIqHB6hbNkpzF/MzUhWQHf3cgXMb+4ei6GzKZuLhF5wurFGHnZ2XpEvM=,iv:+wEb3UwzkeIeWaJ9jxjpRVSrv4IZD1k4lEBvR5ZqfPU=,tag:obN7mzLMhEmwfywPaKFU7Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
