apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PxgQB4qDR2eDR/vwaf2XGopls6KU7g==,iv:C5Ws9vFQIa1+uYX6tuB6rJ1fAj8tD9CbOBihFEbjzos=,tag:ArPaYW/RXwgDTN5QxLSN2A==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRDdIaTlBSzdibUpxUDhX
            TkgrRDFEZlY0ZG9sWkJyTWdOMDJJZ3Z0NkJNCnFrNlpvbXMyd1pyRTZTdmlGTWwr
            UmlEcG41WkF3NmlwTVpjd01NczlMWFEKLS0tIC8wRkxDbHFvcTVRZGxoekNJN1h4
            cnVtTGdyUWNHUmhrdll0MW5zTStIMUUKmobzSyz26BjALnxEAYWd5Hci7Dkn5r37
            J0vmtne5TO6RKePqSofim3P10+vdZT5BUptELwajVX+kYTDuA49o4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T12:01:00Z"
    mac: ENC[AES256_GCM,data:fSiCAp5/ReiPWNtcU2aWMWe3dqXo6kP+52WqwYoNkF0rUUVYX5ge5RQkB9yeWB4+owMN50KbL+MXztvqkd4Alg6nW9fazH/wm7hTQyy0yV7f5/KYhpI+Fs4BT3JebOnIagM0qy5qWAkei1nn7JVOkohhjRVTMee2Dk+MLPeyUG8=,iv:S0/oK81qGvKSOLhhps9K43/8xXCJveiHS1gX+8Dy9Fs=,tag:nySaPPyja4NJw9gRXt5bqA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
