apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kopia
    namespace: kopia
spec:
    interval: 15m
    chart:
        spec:
            chart: kopia
            version: 13.5.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: kopia
    values:
        global:
            stopAll: false
        # https://github.com/DoTheEvo/selfhosted-apps-docker/tree/master/kopia_backup
        workload:
          main:
            podSpec:
              containers:
                main:
                  args:
                    - server
                    - start
                    - --tls-generate-cert
                    - --disable-csrf-token-checks
                    - --address=http://0.0.0.0:{{ .Values.service.main.ports.main.port }}
                    # - --insecure
                    - --server-username={{ .Values.kopia.server_username }}
                    - --server-password={{ .Values.kopia.server_password }}
        TZ: ${TIMEZONE}
        credentials:
             backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_KOPIA}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_KOPIA}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        kopia:
            user: ${ADMIN_USER}
            password: ${KOPIA_SECRET}
            server_username: ${ADMIN_USER}
            server_password: ${ADMIN_PASSWORD}
        service:
            main:
                enabled: true
                type: ClusterIP
        persistence:
            config:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
            cache:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: cache
                      src:
                        enabled: true
                      type: restic
            logs:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: logs
                      src:
                        enabled: true
                      type: restic
            rclone:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: rclone
                      src:
                        enabled: true
                      type: restic
            data:
                enabled: true
                type: nfs
                server: ${IP_TRUENAS}
                path: ${NFS_DATA_KOPIA}
                mountPath: /data
                # mountOptions:
                # - nfsvers=4
                # - tcp
                # - intr
                # - hard
                # - noatime
                # - nodiratime
                # - nolock