apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nitter
    namespace: nitter
spec:
    interval: 15m
    chart:
        spec:
            chart: nitter
            version: 7.1.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: nitter
    values:
        TZ: ${TIMEZONE}

        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_NITTER}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: ${DNS_CLUSTER_CERT_NAME}
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        nitter:
            cache:
                listMinutes: 240
                rssMinutes: 10
            config:
                base64Media: false
                enableDebug: false
                enableRSS: true
                proxy: ""
                proxyAuth: ""
                tokenCount: 10
            general:
                hostname: localhost:10606
                httpMaxConnections: 100
                title: ${NITTER_BANNER}
            preferences:
                hlsPlayback: false
                infiniteScroll: false
                proxyVideos: true
                replaceInstagram: ""
                replaceReddit: ${DOMAIN_LIBREDDIT}
                replaceTwitter: ${DOMAIN_NITTER}
                replaceYouTube: ${DOMAIN_INVIDIOUS}
                theme: twitter_dark
        release_name: nitter
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: 10606
                type: ClusterIP
