apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: onlyoffice-document-server
    namespace: onlyoffice-document-server
spec:
    interval: 15m
    chart:
        spec:
            chart: onlyoffice-document-server
            version: 18.1.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: onlyoffice-document-server
    values:
        TZ: ${TIMEZONE}
        cnpg:
            main:
                backups:
                    credentials: ${S3_NAME}
                    enabled: true
                    revision: ${CNPG_BACKUP_REVISION}
                mode: recovery
                recovery:
                    method: object_store
                    credentials: ${S3_NAME}
                    enabled: true
                    revision: ${CNPG_RECOVERY_REVISION}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_ONLYOFFICE_DOCUMENT_SERVER}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - "{{ .Values.ingress.main.hosts.host }}"
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        release_name: onlyoffice-document-server
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: ${PORT_ONLYOFFICE_DOCUMENT_SERVER}
                type: ClusterIP
