apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: docker
    namespace: docker
spec:
    interval: 15m
    chart:
        spec:
            chart: docker
            version: 9.9.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: docker
    values:
        global:
            stopAll: false
        TZ: ${TIMEZONE}
        credentials:
             backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_DOCKER}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_DOCKER}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Media
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        service:
            main:
                enabled: true
                type: ClusterIP
        persistence:
            config:
                enabled: true
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                        trigger:
                            schedule: 40 0 * * *
                      type: restic
                      cleanupTempPVC: true
                      cleanupCachePVC: true