apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: docker
    namespace: docker
spec:
    interval: 15m
    chart:
        spec:
            chart: docker
            version: 9.9.5
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: docker
    values:
        global:
            stopAll: false
        TZ: ${TIMEZONE}
        credentials:
             backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}

        clusterIssuer:
                selfSigned:
                    enabled: true
                    name: "selfsigned"
        certificate:
          main:
            enabled: true
            certificateIssuer: docker-ca-issuer
            hosts:
              - ${DOMAIN_DOCKER}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_DOCKER}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: docker-ca-issuer
                    #   clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_DOCKER}
                      secretName: root-secret
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        service:
            main:
                enabled: true
                type: ClusterIP
                # loadBalancerIP: ${IP_DOCKER}
        # persistence:
        #     docker-certs-ca:
        #         volsync:
        #             - credentials: ${S3_NAME}
        #               dest:
        #                 enabled: true
        #               name: docker-certs-ca
        #               src:
        #                 enabled: true
        #                 trigger:
        #                     schedule: 40 0 * * *
        #               type: restic
        #               cleanupTempPVC: true
        #               cleanupCachePVC: true
        # volumeClaimTemplates:
        #     docker-certs-client:
        #         volsync:
        #             - credentials: ${S3_NAME}
        #               dest:
        #                 enabled: true
        #               name: docker-certs-client
        #               src:
        #                 enabled: true
        #                 trigger:
        #                     schedule: 40 0 * * *
        #               type: restic
        #               cleanupTempPVC: true
        #               cleanupCachePVC: true
        #     docker:
        #         volsync:
        #             - credentials: ${S3_NAME}
        #               dest:
        #                 enabled: true
        #               name: docker
        #               src:
        #                 enabled: true
        #                 trigger:
        #                     schedule: 40 0 * * *
        #               type: restic
        #               cleanupTempPVC: true
        #               cleanupCachePVC: true