apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: laravel
    namespace: laravel
spec:
    interval: 15m
    chart:
        spec:
            chart: app-template
            version: 14.5.3
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: laravel
    values:

        portal:
            open:
                enabled: true

        image:
            repository: docker.io/bitnami/laravel
            pullPolicy: IfNotPresent
            tag: latest@sha256:0ef79b51719d89484cbdad8294984fd6db4753eca39c0cd72e5f0742219a8da6

        imageMariaDb:
            repository: docker.io/bitnami/mariadb
            pullPolicy: IfNotPresent
            tag: latest@sha256:f3727b7bf6d558c24e72702970cc54cde07568264d155123917b277abf348f4f


        securityContext:
            container:
                runAsNonRoot: false
                readOnlyRootFilesystem: false
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
                UMASK: "0022"
            pod:
                fsGroupChangePolicy: OnRootMismatch


        global:
            stopAll: false

        TZ: ${TIMEZONE}

        # addons:
        #     codeserver:
        #         enabled: true
        #         persistence:
        #             config:
        #                 enabled: true
        #                 mountPath: "/config"
        #         ingress:
        #             enabled: true
        #             hosts:
        #                 - host: ${DOMAIN_LARAVEL}
        #                   paths:
        #                     - path: /code
        #                       pathType: Prefix
        #             tls:
        #                 - certificateIssuer: ""
        #                   clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
        #                   hosts:
        #                     - ${DOMAIN_LARAVEL}
        #                   secretName: ""
        #             integrations:
        #                 certManager:
        #                     enabled: false
        #                     certificateIssuer: ""
        #                 traefik:
        #                     enabled: true
        #                     entrypoints:
        #                         - websecure
        #                     middlewares:
        #                         - name: local
        #                           namespace: traefik
        #                         - name: ${TRAEFIK_MIDDLEWARE}
        #                           namespace: traefik
        #         service:
        #             ports:
        #                 codeserver:
        #                     port: 7011
        #             type: ClusterIP

        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_LARAVEL}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_LARAVEL}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            source-code:
                enabled: true
                targetSelector:
                    main:
                        main:
                            mountPath: /source-code

        service:
            main:
                ports:
                    main:
                        port: 8010
                        targetPort: 8000 
                enabled: true
                type: ClusterIP
            # mariadb:
            #     enabled: true
            #     targetSelector: mariadb
            #     ports:
            #         mariadb:
            #             enabled: true    
            #             port: 3306
            #             targetPort: 3306
            #             targetSelector: mariadb
            #     type: ClusterIP

        workload:
            main:
                podSpec:
                    containers:
                        main:
                            enabled: true
                            env:
                                DB_HOST: http://laravel-app-template-mariadb.laravel.svc.cluster.local
                                DB_PORT: 3306
                                DB_USERNAME: laravel
                                DB_DATABASE: laravel
                                LARAVEL_PORT_NUMBER: 8000
                                LARAVEL_BASE_DIR: /source-code
        # mariadb:
        #     enabled: true
        #     includeCommon: true
        #     # password: "PLACEHOLDERPASSWORD"
        #     # rootPassword: "PLACEHOLDERROOTPASSWORD"
        #     # -- can be used to make an easy accessable note which URLS to use to access the DB.
            # creds:
            #     user: laravel
            #     database: laravel
            mariadb:
                enabled: true
                type: Deployment
                replicas: 1
                podSpec:
                    containers:
                        mariadb:
                            enabled: true
                            primary: true
                            imageSelector: imageMariaDb
                            # type: install
                            env:
                                ALLOW_EMPTY_PASSWORD: yes
                                MARIADB_USER: laravel
                                MARIADB_DATABASE: laravel
                                MARIADB_MASTER_HOST: http://laravel-app-template-mariadb.laravel.svc.cluster.local
                                MARIADB_MASTER_PORT_NUMBER: 3306
                            probes:
                                liveness:
                                    enabled: true
                                    type: http
                                    port: 3306
                                readiness:
                                    enabled: true
                                    type: http
                                    port: 3306
                                startup:
                                    enabled: true
                                    type: tcp
                                    port: 3306