apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: dashy
    namespace: dashy
spec:
    interval: 15m
    chart:
        spec:
            chart: dashy
            version: 8.1.5
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: dashy
    values:
        TZ: ${TIMEZONE}
        addons:
            codeserver:
                enabled: true
                ingress:
                    enabled: true
                    hosts:
                        - host: ${DOMAIN_DASHY_CONFIG}
                          paths:
                            - path: /
                              pathType: Prefix
                    tls:
                        - certificateIssuer: ""
                          clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                          hosts:
                            - ${DOMAIN_DASHY_CONFIG}
                          secretName: ""
                    integrations:
                        certManager:
                            enabled: false
                            certificateIssuer: ""
                        traefik:
                            enabled: true
                            entrypoints:
                                - websecure
                            middlewares:
                                - name: local
                                  namespace: traefik
                                - name: ${TRAEFIK_MIDDLEWARE}
                                  namespace: traefik
                service:
                    ports:
                        codeserver:
                            port: ${PORT_DASHY_CODE_SERVER}
                    type: ClusterIP
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        dashy:
            configDirectoryHostPath: ${DASHY_CONFIG_PATH}
            configDirectoryHostReadOnly: false
            enabled: true
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_0}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Cluster
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            icons:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: app-icons
                      src:
                        enabled: true
                      type: restic
        release_name: dashy
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: ${PORT_DASHY}
                type: ClusterIP
