apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: laravel
    namespace: laravel
spec:
    interval: 15m
    chart:
        spec:
            chart: app-template
            version: 14.5.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: laravel
    values:

        portal:
            open:
                enabled: true

        image:
            repository: docker.io/bitnami/laravel
            pullPolicy: IfNotPresent
            tag: latest@sha256:e013bfa39a44857bc09bf45a76ee9cd412dbba28ad87540504ad62a0a222f89a

        imageMariaDB:
            repository: docker.io/bitnami/mariadb
            pullPolicy: IfNotPresent
            tag: latestsha256:f3727b7bf6d558c24e72702970cc54cde07568264d155123917b277abf348f4f@


        # securityContext:
        #     container:
        #         runAsNonRoot: false
        #         readOnlyRootFilesystem: false
        #         runAsUser: 0
        #         runAsGroup: 0
        #         fsGroup: 0
        #         UMASK: "0022"
        #     pod:
        #         fsGroupChangePolicy: OnRootMismatch


        global:
            stopAll: false

        TZ: ${TIMEZONE}

        # addons:
        #     codeserver:
        #         enabled: true
        #         persistence:
        #             config:
        #                 enabled: true
        #                 mountPath: "/config"
        #         ingress:
        #             enabled: true
        #             hosts:
        #                 - host: ${DOMAIN_LARAVEL}
        #                   paths:
        #                     - path: /code
        #                       pathType: Prefix
        #             tls:
        #                 - certificateIssuer: ""
        #                   clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
        #                   hosts:
        #                     - ${DOMAIN_LARAVEL}
        #                   secretName: ""
        #             integrations:
        #                 certManager:
        #                     enabled: false
        #                     certificateIssuer: ""
        #                 traefik:
        #                     enabled: true
        #                     entrypoints:
        #                         - websecure
        #                     middlewares:
        #                         - name: local
        #                           namespace: traefik
        #                         - name: ${TRAEFIK_MIDDLEWARE}
        #                           namespace: traefik
        #         service:
        #             ports:
        #                 codeserver:
        #                     port: 7011
        #             type: ClusterIP

        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_LARAVEL}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_LARAVEL}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            source-code:
                enabled: true
                targetSelector:
                    main:
                        main:
                            mountPath: /source-code

        service:
            main:
                ports:
                    main:
                        port: 8000 
                enabled: true
                type: ClusterIP
            mariadb:
                enabled: true
                targetSelector: mariadb
                ports:
                    mariadb:
                        enabled: true    
                        port: 3306
                        targetPort: "{{ .Values.service.mariadb.ports.mariadb.port }}"
                        targetSelector: mariadb
                type: ClusterIP

        workload:
            main:
                podSpec:
                    containers:
                        main:
                            enabled: true
                            primary: true
                            
                            # type: install
                            env:
                                DB_HOST: mariadb
                                DB_PORT: "{{ .Values.service.mariadb.ports.mariadb.port }}"
                                DB_USERNAME: "{{ .Values.workload.main.podSpec.containers.mariadb.env.MARIADB_USER }}"
                                DB_DATABASE: "{{ .Values.workload.main.podSpec.containers.mariadb.env.MARIADB_DATABASE }}"
                                LARAVEL_PORT_NUMBER: "{{ .Values.service.main.ports.main.port }}"
                                LARAVEL_BASE_DIR: /source-code
                        mariadb:
                            enabled: true
                            # primary: true
                            imageSelector: imageMariaDB
                            # type: install
                            env:
                                ALLOW_EMPTY_PASSWORD: yes
                                MARIADB_USER: laravel
                                MARIADB_DATABASE: laravel
                            probes:
                                liveness:
                                    enabled: true
                                    type: http
                                    port: "{{ .Values.service.mariadb.ports.mariadb.targetPort }}"
                                readiness:
                                    enabled: true
                                    type: http
                                    port: "{{ .Values.service.mariadb.ports.mariadb.targetPort }}"
                                startup:
                                    enabled: true
                                    type: tcp
                                    port: "{{ .Values.service.mariadb.ports.mariadb.targetPort }}"