apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: whoogle
    namespace: whoogle
spec:
    interval: 15m
    chart:
        spec:
            chart: whoogle
            version: 11.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: whoogle
    values:
        TZ: ${TIMEZONE}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_WHOOGLE}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_WHOOGLE}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            config:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
        service:
            main:
                enabled: true
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                # WHOOGLE_ALT_RD: ${DOMAIN_LIBREDDIT}
                                WHOOGLE_ALT_YT: ${DOMAIN_INVIDIOUS}
                                WHOOGLE_CONFIG_ALTS: true
                                WHOOGLE_CONFIG_COUNTRY: US
                                WHOOGLE_CONFIG_GET_ONLY: false
                                WHOOGLE_CONFIG_NEW_TAB: true
                                WHOOGLE_CONFIG_SAFE: true
                                WHOOGLE_CONFIG_STYLE: ""
                                WHOOGLE_CONFIG_THEME: dark
                                WHOOGLE_CONFIG_TOR: false
                                WHOOGLE_CONFIG_URL: https://${DOMAIN_WHOOGLE}
