apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: radarr
    namespace: radarr
spec:
    interval: 5m
    chart:
        spec:
            chart: radarr
            version: 23.27.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            # install:
            #     createNamespace: true
            #     crds: CreateReplace
            #     remediation:
            #         retries: 3
            # upgrade:
            #     crds: CreateReplace
            #     remediation:
            #         retries: 3
    values:
        TZ: ${TIMEZONE}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_RADARR}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Media
                        widget:
                            custom:
                                key: ${API_RADARR}
                            enabled: true
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                        traefik:
                            enabled: true
                            middlewares:
                                - name: ${TRAEFIK_MIDDLEWARE}
                                  namespace: traefik
        persistence:
            config:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                        trigger:
                            schedule: 40 0 * * *
                      type: restic

            media:
                enabled: true
                type: nfs
                server: ${IP_TRUENAS}
                path: "${NFS_DATA_MEDIA}"
                mountPath: "/media"
            backup:
                enabled: true
                type: nfs
                server: ${IP_TRUENAS}
                path: "${NFS_DATA_BACKUP}"
                mountPath: "/backup"
        service:
            main:
                enabled: true
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                RADARR__AUTHENTICATION_METHOD: External
