apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: backuppc
    namespace: backuppc
spec:
    interval: 15m
    chart:
        spec:
            chart: backuppc
            version: 8.5.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: backuppc
    values:
        global:
            stopAll: true
        TZ: ${TIMEZONE}
        credentials:
             backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_BACKUPPC}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_BACKUPPC}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        backuppc:
            smtp:
                auto_from: false
                host: http://protonmail-bridge.protonmail-bridge.svc.cluster.local/
                port: ${PROTONMAIL_PORT_SMTP}
                domain: protonmail.com
                maildomain: protonmail.com
                auth: none
                user: ${PROTONMAIL_USER}
                pass: ${PROTONMAIL_PASSWORD}
                tls: false
                starttls: false
                tlscertcheck: false
        service:
            main:
                enabled: true
                type: ClusterIP
        # persistence:
            # config:
            #     volsync:
            #         - credentials: ${S3_NAME}
            #           dest:
            #             enabled: true
            #           name: config
            #           src:
            #             enabled: true
            #           type: restic
            # ssh:
            #     volsync:
            #         - credentials: ${S3_NAME}
            #           dest:
            #             enabled: true
            #           name: ssh
            #           src:
            #             enabled: true
            #           type: restic
            # logs:
            #     volsync:
            #         - credentials: ${S3_NAME}
            #           dest:
            #             enabled: true
            #           name: logs
            #           src:
            #             enabled: true
            #           type: restic
            # data:
            #     volsync:
            #         - credentials: ${S3_NAME}
            #           dest:
            #             enabled: true
            #           name: data
            #           src:
            #             enabled: true
            #           type: restic
            # data:
            #     enabled: true
            #     type: nfs
            #     server: ${IP_TRUENAS}
            #     path: ${NFS_DATA_BACKUPPC}
            #     mountPath: /data
                # mountOptions:
                # - nfsvers=4
                # - tcp
                # - intr
                # - hard
                # - noatime
                # - nodiratime
                # - nolock