apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: custom-app-template
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/custom-app-template/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

