apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lzsbTLdzZ6bSGty85xe01FM8N+024fwnF1q/WlO2izAa0DYRQ7hqmTUE11l1s7q25QUjbMJlusPVxiKqP5J6b3XxV0aCir1c55vGki8uJ9VPtXjNrnu93BF6VyyYLQv5iLhgkLP0HGOQvTyZhjDRPnFqWSeG/gj0T0eRKoOCUgbTQpKiXVODp22LM8YuzP0dWStLvESNcqDv0nnHyorbpYtLwf5liclRBecQ1AQQhyYQJmzXNNxy53WTMFxVbAqT7eIKo87laBlvLoeDLbTom6AzcY7Vqgf82GBIo1hJUozJT/ML1oHyodHbWlXuzYL4sC/MEwrKTdlj3kK5eNa7Tts3ujD5hZmf4YcOSXYFaBvh5xMHVffCv4RqJtjx3GTk,iv:PZwtTGG7acZDEjzKeEtfK9p/R2fStWPFMWtyzm9/qOs=,tag:XsSOO5y/Oz85AGNb/elwQw==,type:str]
    identity.pub: ENC[AES256_GCM,data:7HHGm8FKBrdv4WGKsChp4OcS7druIIPdnoDNv3ksAHxQPq6Fk+k7UQglLzA5BEkHeG8+CAh8AFfy6SYZPWkzNHATQbahonBMWSrvqYOTYP/1H052qhmJ6l2MP2UR5Kng/Scp/OAFjQ89C+ssi4fgMY06U4O7Ji2mQcXvVPA4ZzDjMOWhkN8GZ83hXsITEX6zFA8AoprWnVin61R/78NckY9eiz1lYGF4vekeF3Aodo0mXNZBPS4lKksVynaX3RFDfNMPTu2s8/XkX4La4w==,iv:8cLLz4oIgvT6wccJBKRr6t5RbFQDd0hB+RA5rECvg1g=,tag:SbXDDubLr3cqF0+CV8OGUQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:BrVUKtRCD+bPuKFtz15XTSundp8AkuDlAgwJucPN0l5Xb6ZKuReWvWUXyyZk2pX/3FQFj5sAkYtO9sNPBQmR7VsjBQqyhNleWtJIXkg5uAJ3IKimPgjHEWLSuEBlFJHkssNjObnhUeFUzYVxUm1CE6uyYekWf2epZAejAFzUcfOyMqXW3YAkBWX02f2a496f/gXl28oOdu+Aj0Un5GdstbhI02K/6T5qflxv,iv:1iYaPMYq6H5wX6UGiC+e+ctNhGD69hr2N20ZRGQoGus=,tag:0u3vRObqHkLJGR52i8wACw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXQ0d2FyaThmbHAwZWEy
            UEM5TmNTV1BYdDVtMy9pTFEydVhBME1rNEU0Cnl5OS9yUFMxUlZkUzI0WFIzQWFO
            Z2p2RC9jaEdzNHRZMW1zeDhCMlQ5VTAKLS0tIHVmNS82UG5Od3p1cXVvTGgvelhJ
            UzQ4VkxPOHdycFcrWmovMkpUenluRGcK3TMNmx+NCLjxcloFVjINXKYrhcxVZe7m
            fhOgcGBlJcQerCoufnYsRiAI5i0tVFDDZH+c4iwsXKgP8JPVUbeHvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T22:49:43Z"
    mac: ENC[AES256_GCM,data:9yo4KT67nko/39f8/XCYmyOjh83zRgn1C9zWq9a/5TTeKozylescXlE2sMiH04OL5bhm1wFLEc5CUXQ3tsg6qNnFGtPDWdjKrvutboohHzAbBG1BQLRaFBMkSA3GryvoUf/Hvtkk5ORUFx/cZtmcRQG+RrgppFl914VxbFzBi7I=,iv:k/ks76VYdHoNUNguJUZkPuyHCmNdLP1iIKADGwtCxn8=,tag:Za9w3RbFe4xBeqXRfk9diw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
