apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:t/SLZHcaDNC4T8odKAfVEqylajK3NWmKXAkcdT2LLX6uLSB7kAtfnS/1bhXd/rg94wkvrnQ6DLjOtkW7ztsdC1KJfOpJI9IjiVE0kf7kgrwqBPAeZxd+lIzUde2uY1PzXNpxT+aYi/E+JBxZ4FLnn24U/cQ+bG3qbTQGGpkxhlKj699ctfIca5umCAT8LxXN7+l1Hiu+HuTLdJOb5cUigxOL8mBz2/Lzomqsja0ErCguI+auCx4qRlyZGPlhbg8bZAPvNkDrNo1k5DJ0rPNHMMM4iqTYC/pMssEKS1B8a63be49mwz3Wq98UMu6kInkXFO2U7qvmseAItcyMdiFs89XwPHPbs7Jcy8YZYWhYDvs7nbe2MYLHLhIDB/vOdDcI,iv:WwqVZ9jPSrtjucrNYYMGtAfqSwsiEvNZvyxqCY7gryU=,tag:m5aG8zhn9R3l5e7rOlZZTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:6VIHoLPvtdUNFyZXYd4QsOfAjb6h8wHTdcwBfnYYv2mf4QMerrvnRSw1aSa6c/HB20ezjadsD1QdSrtstehh5hl8rvGwJeqYXsJiqD4t7MvqcBkCIaaZa/nzJ+f0pYCeXtQhqwUWcAeZMZPUndfsgbq0L2K7oTK3C2VnwDKvduvguvBo6tbQjLmDsLJhGMce0rdT6T4r4tnpLk6mV+xrTivSwfuyh4Uim0L693BzwfvLjYm9fz4ruTQkeJSSZNeRTJVsuIqpb82hKPSc1g==,iv:iD3EovPjAMVnIqEKIeseSG5gk+Qgos6Gk7qRyqLFr28=,tag:4lDU1CZc/R5QJBSF1QGBKQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VH/1Y5AA2c3jESm5yoO5mEerbaBmU7I+G29gG7fm4Yu98nguLdwvZ/i44qZlUxACexl3ImjUcnsyAhFFdjh0cGJ6346IzBScMMguUENBSo1aNh2m/i8cpMfmw7+htA8GT9sqiiIVEQop0LnRXTT5UoT0IDoFMkbcYlRT+f/WgKFSvtdznpbXmxiND5DOD9Um3creRlj+GsIBUZN7l29qePwx5N0j9M/WWS/Z,iv:3pTq7prs6zlWL1WU0daZEU+J8h1bYSh3uyzack1qhjE=,tag:FEzfXxrIVSxvsQLVFrXqhQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYVFSZStJalhRY1RaQWlr
            cDNXTW1CYXFFUTVuM2ZwUFhWRXNVN2ZHV21vCnhodHdURFArNmRsb2IzNFJ0QXZ4
            SERBYlN2TVVnU1FkQlAycFJiZHpPNFkKLS0tIGVvd1lrbndnNGpaLzBXSi9KZnRZ
            a0R5Y29jRUtNbzk1cjFMNm9rUzVJODQKx8TGGZ1LLHWOZPm4uzzoi1QL3MxyR75Z
            u8tlrt0HQlYUusClTOVflQyILpWAM5Dt0frMhP5PDo37zytOqgLANg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T18:17:39Z"
    mac: ENC[AES256_GCM,data:/ZvLhqDfz9h1u99djS/qvKm/jwFz0p1BZE4qSAp8PS0GtEZPKys1bst6xzz0mkRgn4u1SSY4+RvgDHZUnaJOt9kcne/IN4y4dv53F2T5WqnFRyREFck+Y2uaGmEetndkz8hJSnqeRxXkoEkite0ty/T/9B+k1dn/QoIt1uV6GW0=,iv:cLLzntkPQrqAyZol+5/UpJgQgd6Ds4J0nawxVXPrH9s=,tag:rP7g24ZYmx2dD+ul+s+SZg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
