apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:qw+sNswrYLlyoOe00VBCcnExCzvmL2yJamuNxPq0lehYfXfadha2ZmAqBHrwAElhWontgo5PJMBr9HPS1wBHIjihn5nuQbN1PzJD8oOiMQj755ZHMLG0V/NtGt0dmQQsev3AISxKymZtP88NRLNmMUcIt1rmZASr2Na8RBidFHKkJ5GQeB0ARaLbTDBFfSX0yn0LWxRPT8N3zU8C37zcHrvx/L7vxpe0m+yndqtQ2GncANE65nF55KiMvB0Fsof/m9fvG0TbWKjdiy5bc2PSxhbB4THI3+3L9q9CvtgEqu8MiYAJSWDzi78zrkVZeh3zgsWyZLX4nR9x4Kq0pBe2SmEOzssBdWwPc38BhoaGegYnJsPSk7PDm5Qtr7Q1aV+N,iv:XI3Obo5AgTAK6nS1qGOoC0lzOCDG0cScfm6HyylHbaw=,tag:c1x9t/dNleIisyGOX4+VVQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:oncYrJUo7dy+TU/uqx93Eu9yEjL/fvrnOgSvxAK6pvDTP2isbGv4B/Dvn6Rfs1UtsHmuRpPe9+clBhplGdfOrbME9AHYjo0q6LL3DmG4F6alv/xsSYOYjrjcocihb0QqUOcGsldj7ozj5BkaVQetzEKpGm9URq/AJCALJBshsZEuqxG+o19VDQCpFbbKMJ/dav+MX47iVJwcSTuTnXW/zKFC8FXCQoJnAqpSMUR3lBVB6t3G4AFaCqSdSsBJCq/8sWAdm/qpLmvHkuLdkA==,iv:9wa+VZL8RwsSjEC3gSMmspwxEYjfAvp3Yh2WhcwBxYg=,tag:OFB6RFGNHsqFEMxBpk5hFA==,type:str]
    known_hosts: ENC[AES256_GCM,data:KWYMLlPYnU0bbfHSXKumz+DkrO+ozB2BNQh+07pa2qk4JVMpxY1uJ69Xj3tbSr1sRfS6lncPnrpgZSf+D8tWfQwOAqx0dbkAoAQ3hQQ69bhxPmtvLepNwFG47qLIfgfHE0ALAw48ZGRKmELj7zjnM6IVt/2bD5geMq+ROZtnnxCenNjJM9/0a1gx05/yYuD8NUfYvnEoMs9L1IxwZaSPMd2Fjd3Z1SGreI3j,iv:ekiDyWezGee8laLYZUIf7yCxBTud7FNH85bYMthkFMM=,tag:UnlKr3gJWhdOBEFpK63Vtw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1hrkgnfpsl76mkvhm2r5z57x3ta0tzk7de9x6eyq4s0cr7dkpzgyqyzd95n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UWxwN3ZhUVhMQUdoTkpZ
            dnlTY04zUDRRWEFwcWhScmhzUVdIMXNFaHdRCjloYmt1NDRPK2JPUG9xUGJnS3dB
            NUlJNXpZb2RKb2djZXRKL2hFY0dxd0kKLS0tIDIzOGpXZWFsUUJmZE5RclZ3NFhS
            MmE5VXNTTDVjMTVzbjRkZnM4U2ZVSDQKkxdbQuI1nGJeBJTeBvSm7670cnwDYIBn
            aWecnjRVWhFId2SJvubnclvOrpXG8XucxJ1QknpcWFTisaS9Fev+yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T20:10:30Z"
    mac: ENC[AES256_GCM,data:E2bP0C+ShUdCHxee+e4U2eZS5M5fEA2kE4qEF30zP6HSDDDNX5EgdXvoQkU8dBSHayzJ6HeC+h89qze2mZab0YOsyu5rIJYh7vObzgp0FV2IHJTzrB8icYYVPOkzvu4L0ctZCrssNmpHY2bvKxs6jsaPLd04Q4vKbrnvs2c1Xqs=,iv:ZGX/EB/iisnX5W0yLtdOb+bOh/MrkI5rOgcwxQ8KZKk=,tag:MMrExqgJADk3C3+yzd5X7A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
