apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: clonezilla
    namespace: clonezilla
spec:
    interval: 15m
    chart:
        spec:
            chart: app-template
            version: 14.5.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: clonezilla
    values:
        image:
            repository: docker.io/warfront1cz/clonezilla
            tag: 3.2.0-5-amd64@sha256:24ed602a810577365742b34213f4c1223948fcd35e1fd9ba377e75dd15d1cf31
            pullPolicy: IfNotPresent
        global:
            stopAll: true
        TZ: ${TIMEZONE}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_CLONEZILLA}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_CLONEZILLA}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        # persistence:
        #     config:
        #         volsync:
        #             - credentials: ${S3_NAME}
        #               dest:
        #                 enabled: true
        #               name: config
        #               src:
        #                 enabled: true
        #               type: restic
        service:
            main:
                ports:
                    main:
                        protocol: http
                        port: 11247 
                enabled: true
                type: ClusterIP
        portal:
            open:
                enabled: true