apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: traefik
    namespace: traefik
spec:
    interval: 15m
    chart:
        spec:
            chart: traefik
            version: 27.0.14
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: traefik
    values:
        TZ: ${TIMEZONE}
        additionalArguments:
            - --serverstransport.insecureskipverify=true
            - --providers.kubernetesingress.allowexternalnameservices=true
        defaultCertificate: ""
        expertIngressClass: false
        globalArguments:
            - --global.checknewversion
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_TRAEFIK}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Cluster
                        widget:
                            enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: ${DNS_CLUSTER_CERT_NAME}
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        ingressClass:
            enabled: false
            fallbackApiVersion: ""
            isDefaultClass: false
        ingressRoute:
            dashboard:
                enabled: true
        logs:
            access:
                enabled: false
                fields:
                    general:
                        defaultmode: keep
                    headers:
                        defaultmode: drop
                filters:
                    minduration: 10ms
                    retryattempts: true
                    statuscodes: 200,300-302
                format: common
            general:
                format: common
                level: ERROR
        middlewares:
            forwardAuth:
                - address: http://authelia.authelia.svc.cluster.local:${PORT_AUTHELIA}/api/verify?rd=https://${DOMAIN_AUTHELIA}/
                  authRequestHeaders: []
                  authResponseHeaders:
                    - Remote-User
                    - Remote-Group
                    - Remote-Name
                    - Remote-Email
                  authResponseHeadersRegex: ""
                  name: ${TRAEFIK_MIDDLEWARE}
                  tls:
                    insecureSkipVerify: false
                  trustForwardHeader: true
        operator:
            register: true
        podOptions:
            automountServiceAccountToken: true
        portalhook:
            enabled: true
        providers:
            kubernetesCRD:
                enabled: true
            kubernetesIngress:
                enabled: true
                publishedService:
                    enabled: true
        release_name: traefik
        service:
            main:
                enabled: true
                loadBalancerIP: ${IP_TRAEFIK}
                ports:
                    main:
                        forwardedHeaders:
                            enabled: false
                        port: ${PORT_TRAEFIK}
                        protocol: http
                        proxyProtocol:
                            enabled: false
                type: LoadBalancer
            tcp:
                enabled: true
                externalTrafficPolicy: Cluster
                loadBalancerIP: ${IP_TRAEFIK}
                ports:
                    web:
                        enabled: true
                        forwardedHeaders:
                            enabled: false
                            insecureMode: false
                        port: 80
                        protocol: http
                        proxyProtocol:
                            enabled: false
                            insecureMode: false
                        redirectPort: 443
                        redirectTo: websecure
                    websecure:
                        enabled: true
                        forwardedHeaders:
                            enabled: false
                            insecureMode: false
                        port: 443
                        protocol: https
                        proxyProtocol:
                            enabled: false
                            insecureMode: false
                        tls:
                            enabled: true
                type: LoadBalancer
        serviceAccount:
            main:
                enabled: true
                primary: true
        tlsOptions:
            default:
                cipherSuites:
                    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
                    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
                    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
                    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
                    - TLS_AES_128_GCM_SHA256
                    - TLS_AES_256_GCM_SHA384
                    - TLS_CHACHA20_POLY1305_SHA256
                curvePreferences:
                    - CurveP521
                    - CurveP384
                    - X25519
                minVersion: VersionTLS12
                sniStrict: false
        warning:
            warningconfim: true
