apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: qbittorrent
  namespace: qbittorrent

spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 23.3.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  #timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: ${TIMEZONE}

    addons:
      codeserver:
        enabled: true
        ingress:
          main:
            enabled: true
            ingressClassName: external
            integrations:
              certManager:
                enabled: true
                certificateIssuer: ${DNS_NAME}
            hosts:
              - host: ${SUBDOMAIN_QBITTORRENT_CFG}.${DOMAIN_0}
        service:
          ports:
            codeserver:
              port: ${PORT_QBITTORRENT_CODE_SERVER}
          type: ClusterIP

    credentials:
      backblaze:
        accessKey: ${S3_ACCESS_KEY}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_ENCRYPTION_KEY}
        name: ${S3_NAME}
        path: ""
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_URL}

    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          homepage:
            enabled: true
            group: Admin - Media
            widget:
              enabled: false
          certManager:
            enabled: true
            certificateIssuer: ${DNS_NAME}
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "${SUBDOMAIN_AUTHELIA}.${DOMAIN_0}"
              # Can be left default in most cases
              responseHeaders: []
        hosts:
          - host: ${SUBDOMAIN_QBITTORRENT}.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: ${S3_NAME}
            dest: #VolSync Destination (Restore)
              enabled: true
            src: #VolSync Source (Backup)
              enabled: true
              trigger:
                schedule: 40 0 * * *
      media:
        enabled: true
        type: nfs
        server: ${IP_TRUENAS}
        path: "${NFS_DATA_MEDIA}"
        mountPath: "/media"

    service:
      main:
        enabled: true
        loadBalancerIP: ${IP_QBITTORRENT}
        type: LoadBalancer
        integrations:
          metallb:
            enabled: true

      torrent:
        enabled: true
        loadBalancerIP: ${IP_QBITTORRENT}
        ports:
          torrent:
            enabled: true
            port: ${PORT_QBITTORRENT_TORRENT}
            protocol: tcp
        type: LoadBalancer
        integrations:
          metallb:
            enabled: true

