apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: renovate
    namespace: renovate
spec:
    interval: 15m
    chart:
        spec:
            chart: renovate
            version: 1.4.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: renovate
