apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: sonarr
    namespace: sonarr
spec:
    interval: 15m
    chart:
        spec:
            chart: sonarr
            version: 23.6.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: sonarr
    values:
        TZ: ${TIMEZONE}
        global:
            stopAll: false 
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_SONARR}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_SONARR}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Media
 
                        widget:
                            custom:
                                key: ${API_SONARR}
                            enabled: true
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            # config:
            #     volsync:
            #         - credentials: ${S3_NAME}
            #           dest:
            #             enabled: true
            #           name: config
            #           src:
            #             enabled: true
            #             trigger:
            #                 schedule: 40 0 * * *
            #           type: restic
            #           cleanupTempPVC: true
            #           cleanupCachePVC: true
            media:
                enabled: true
                type: nfs
                server: ${IP_TRUENAS}
                path: "${NFS_DATA_MEDIA}"
                mountPath: "/media"
            backup:
                enabled: true
                type: nfs
                server: ${IP_TRUENAS}
                path: "${NFS_DATA_BACKUP}"
                mountPath: "/backup"
        service:
            main:
                enabled: true
                type: ClusterIP
        updated: true
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                SONARR__AUTHENTICATION_METHOD: ""
                                SONARR__PORT: '{{ .Values.service.main.ports.main.port }}'

