apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: audacity
    namespace: audacity
spec:
    interval: 15m
    chart:
        spec:
            chart: audacity
            version: 16.4.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        image:
            tag: 3.7.7@sha256:c43acf99bfe78ea2913f3df8503a11bcbcb90e6e203e2da027b37305dcf10f81

        global:
            stopAll: false

        TZ: ${TIMEZONE}
        credentials:
             backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}

        ingress:
            main:
                enabled: true
                ingressClassName: external
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Media
                        widget:
                            enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: ${DNS_NAME}
                    nginx:
                        enabled: true
                        auth:
                            type: "authelia"
                            internalHost: "authelia.authelia.svc.cluster.local:9091"
                            externalHost: "${SUBDOMAIN_AUTHELIA}.${DOMAIN_0}"
                            # Can be left default in most cases
                            responseHeaders: []
                hosts:
                - host: ${SUBDOMAIN_AUDACITY}.${DOMAIN_0}

        service:
            main:
                ports:
                    main:
                        port: 10033
                        targetPort: 3001
            http:
                enabled: true
                ports:
                    http:
                        enabled: true
                        port: 10032
                        protocol: http
                        targetPort: 3000

        persistence:
            # config:
            #     volsync:
            #         - credentials: ${S3_NAME}
            #           dest:
            #             enabled: true
            #           name: config
            #           src:
            #             enabled: true
            #             trigger:
            #                 schedule: 40 0 * * *
            #           type: restic
            #           cleanupTempPVC: true
            #           cleanupCachePVC: true
            data:
                enabled: true
                type: nfs
                server: ${IP_TRUENAS}
                path: ${NFS_DATA_AUDACITY}
                mountPath: /media
                # mountOptions:
                # - nfsvers=4
                # - tcp
                # - intr
                # - hard
                # - noatime
                # - nodiratime
                # - nolock