apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: netbootxyz
    namespace: netbootxyz
spec:
    interval: 15m
    chart:
        spec:
            chart: netbootxyz
            version: 6.5.3
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: netbootxyz
    values:
        global:
            stopAll: false
        TZ: ${TIMEZONE}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        service:
            tftp:
                type: LoadBalancer
                loadBalancerIP: ${IP_NETBOOTXYZ}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_NETBOOTXYZ}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_NETBOOTXYZ}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
            assets:
                enabled: true
                hosts:
                    - host: ${DOMAIN_NETBOOTXYZ_ASSETS}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_NETBOOTXYZ_ASSETS}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
            tftp:
                enabled: true
                hosts:
                    - host: ${DOMAIN_NETBOOTXYZ_TFTP}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_NETBOOTXYZ_TFTP}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            config:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                        trigger:
                            schedule: 40 0 * * *
                      type: restic
                      cleanupTempPVC: true
                      cleanupCachePVC: true
            assets:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: assets
                      src:
                        enabled: true
                        trigger:
                            schedule: 40 0 * * *
                      type: restic
                      cleanupTempPVC: true
                      cleanupCachePVC: true