apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-jbsoum-org
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/dev-jbsoum-org/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
