---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    service:
      tcp:
        loadBalancerIP: ${TRAEFIK_IP}
        ingress:
            main:
              enabled: true
              hosts:
                  - host: ${DOMAIN_TRAEFIK}
                    paths:
                      - path: /
                        pathType: Prefix
              integrations:
                  certManager:
                      enabled: false
                      certificateIssuer: ""
                  homepage:
                      enabled: true
                      group: Admin - Cluster
                      widget:
                          enabled: false
                  traefik:
                      allowCors: false
                      enabled: true
                      entrypoints:
                          - websecure
                      middlewares:
                          - name: ${TRAEFIK_MIDDLEWARE}
              tls:
                    clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                    hosts:
                      - ${DOMAIN_TRAEFIK}
        middlewares:
          ipWhiteList:
            - name: local
              sourceRange:
                - 172.16.0.0/16
                - 172.17.0.0/16
                - 10.11.10.0/24
                - 10.11.70.0/24
          forwardAuth:
              - name: ${TRAEFIK_MIDDLEWARE}
                address: http://authelia.authelia.svc.cluster.local:${PORT_AUTHELIA}/api/verify?rd=https://${DOMAIN_AUTHELIA}/
                authRequestHeaders: []
                authResponseHeaders:
                  - Remote-User
                  - Remote-Group
                  - Remote-Name
                  - Remote-Email
                authResponseHeadersRegex: ""
                tls:
                  insecureSkipVerify: false
                trustForwardHeader: true
