---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ## set stopAll to "true" if you do not want to use traefik
    # and/or disable its service
    global:
      stopAll: false
    defaultCertificate: "domain-0-wildcard"
    service:
      main:
        enabled: true
        loadBalancerIP: ${TRAEFIK_IP}
      tcp:
        enabled: true
        loadBalancerIP: ${TRAEFIK_IP}
    # ## For navidrome authentication
    # routers:
    #   navidrome:
    #     rule: Host(`${DOMAIN_NAVIDROME}`)
    #     entrypoints: https
    #     middlewares: ${TRAEFIK_MIDDLEWARE}
    #   navidrome-subsonic:
    #     rule: Host(`${DOMAIN_NAVIDROME}`) && PathPrefix(`/rest/`) && !Query(`c`, `NavidromeUI`)
    #     entrypoints: https
    #     middlewares: ${TRAEFIK_MIDDLEWARE}
    middlewares:
      forwardAuth:
        - name: ${TRAEFIK_MIDDLEWARE}
          address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://${DOMAIN_AUTHELIA}/
          authResponseHeaders:
            - Remote-User
            - Remote-Group
            - Remote-Name
            - Remote-Email
          tls:
            insecureSkipVerify: false
          trustForwardHeader: true
      # ipWhiteList:
      #   - name: local
      #     sourceRange:
      #       - 172.16.0.0/16
      #       - 172.17.0.0/16
      #       - 10.11.0.0/16
    ingress:
        main:
          enabled: true
          hosts:
              - host: ${DOMAIN_TRAEFIK}
                paths:
                  - path: /
                    pathType: Prefix
          integrations:
              homepage:
                  enabled: true
                  group: Admin - Cluster
                  widget:
                      enabled: false
              certManager:
                  enabled: false
                  certificateIssuer: ""
              traefik:
                  enabled: true
                  entrypoints:
                      - websecure
                  middlewares:
                      - name: ${TRAEFIK_MIDDLEWARE}
                        namespace: traefik
          tls:
              - certificateIssuer: ""
                clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                hosts:
                  - ${DOMAIN_TRAEFIK}
