apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    interval: 15m
    chart:
        spec:
            chart: vaultwarden
            version: 28.8.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: vaultwarden
    values:
        TZ: ${TIMEZONE}
        betaImage:
            pullPolicy: IfNotPresent
            repository: ghcr.io/timshel/vaultwarden
            tag: 1.30.5-9
        cnpg:
            main:
                backups:
                    credentials: ${S3_NAME}
                    enabled: true
                    revision: ${CNPG_BACKUP_REVISION}
                mode: recovery
                recovery:
                    method: object_store
                    credentials: ${S3_NAME}
                    enabled: true
                    revision: ${CNPG_RECOVERY_REVISION}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_VAULTWARDEN}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_VAULTWARDEN}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Utilities
                        widget:
                            enabled: false
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
                required: true
        persistence:
            data:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: true
                      type: restic
        release_name: vaultwarden
        service:
            main:
                enabled: true
                ports:
                    main:
                        port: ${PORT_VAULTWARDEN}
                type: ClusterIP
        vaultwarden:
            admin:
                disableAdminToken: false
                enabled: true
                token: ""
            allowInvitation: true
            allowSignups: false
            attachmentLimitOrg: ""
            attachmentLimitUser: ""
            defaultInviteName: ${VAULTWARDEN_BANNER}
            emailAttempts: 3
            emailTokenExpiration: 600
            enableWebVault: true
            hibpApiKey: ""
            icons:
                cache: 2.592e+06
                disableDownload: false
                token: 2.592e+06
            log:
                file: ""
                level: info
            orgCreationUsers: all
            push:
                enabled: false
            requireEmail: false
            showPasswordHint: true
            signupwhitelistenable: false
            smtp:
                authMechanism: Plain
                enabled: true
                from: ${PROTONMAIL_USER}
                fromName: ${ADMIN_EMAIL_FROM}
                heloName: ""
                host: protonmail-bridge.protonmail-bridge.svc.cluster.local
                invalidCertificate: false
                invalidHostname: true
                password: ${PROTONMAIL_PASSWORD}
                port: ${PROTONMAIL_PORT_SMTP}
                security: starttls
                timeout: 15
                user: ${PROTONMAIL_USER}
            verifySignup: true
            yubico:
                enabled: false
