apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: lldap
    namespace: lldap
spec:
    interval: 15m
    chart:
        spec:
            chart: lldap
            version: 7.6.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: lldap
    values:
        global:
            stopAll: false
        TZ: ${TIMEZONE}
        cnpg:
            main:
                mode: recovery
                backups:
                    credentials: ${S3_NAME}
                    enabled: true
                    revision: "v2"
                recovery:
                    method: object_store
                    credentials: ${S3_NAME}
                    enabled: true
                    revision: "v1"
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_LLDAP}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - certificateIssuer: ""
                      clusterCertificate: ${DNS_CLUSTER_CERT_NAME}
                      hosts:
                        - ${DOMAIN_LLDAP}
                      secretName: ""
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Cluster
                    certManager:
                        enabled: false
                        certificateIssuer: ""
                    traefik:
                        enabled: true
                        middlewares:
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            data:
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: config
                      src:
                        enabled: false
                        trigger:
                            schedule: 40 0 * * *
                      type: restic
                      cleanupTempPVC: true
                      cleanupCachePVC: true
        service:
            ldap:
                enabled: true
                type: ClusterIP
            main:
                enabled: true
                type: ClusterIP
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                LLDAP_HTTP_PORT: '{{ .Values.service.main.ports.main.port }}'
                                LLDAP_HTTP_URL: https://${DOMAIN_LLDAP}
                                LLDAP_LDAP_BASE_DN: dc=${DC_SUBDOMAIN},dc=${DC_DOMAIN}
                                LLDAP_LDAP_PORT: '{{ .Values.service.ldap.ports.ldap.port }}'
                                LLDAP_LDAP_USER_DN: ${ADMIN_USER}
                                LLDAP_LDAP_USER_EMAIL: ${ADMIN_EMAIL}
                                LLDAP_LDAP_USER_PASS: ${ADMIN_PASSWORD}
                                LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: false
                                LLDAP_SMTP_OPTIONS__FROM: LLDAP Admin <sender@protonmail.com>
                                LLDAP_SMTP_OPTIONS__PASSWORD: ${PROTONMAIL_PASSWORD}
                                LLDAP_SMTP_OPTIONS__PORT: ${PROTONMAIL_PORT_SMTP}
                                LLDAP_SMTP_OPTIONS__REPLY_TO: Do not reply <noreply@localhost>
                                LLDAP_SMTP_OPTIONS__SERVER: http://protonmail-bridge.protonmail-bridge.svc.cluster.local
                                LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: STARTTLS
                                LLDAP_SMTP_OPTIONS__USER: ${PROTONMAIL_USER}
                                LLDAP_VERBOSE: false
                                smtp: true
