apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: watchyourlan
    namespace: watchyourlan
spec:
    interval: 15m
    chart:
        spec:
            chart: watchyourlan
            version: 9.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: watchyourlan
    values:
        TZ: ${TIMEZONE}
        credentials:
            backblaze:
                accessKey: ${S3_ACCESS_KEY}
                bucket: ${S3_BUCKET}
                encrKey: ${S3_ENCRYPTION_KEY}
                name: ${S3_NAME}
                path: ""
                secretKey: ${S3_SECRET_KEY}
                type: s3
                url: ${S3_URL}
        ingress:
            main:
                enabled: true
                hosts:
                    - host: ${DOMAIN_WATCHYOURLAN}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    homepage:
                        enabled: true
                        group: Admin - Cluster
                        widget:
                            enabled: false
                    certManager:
                        enabled: true
                        certificateIssuer: ${DNS_CLUSTER_CERT_NAME}
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        middlewares:
                            - name: local
                              namespace: traefik
                            - name: ${TRAEFIK_MIDDLEWARE}
                              namespace: traefik
        persistence:
            data:
                enabled: true
                mountPath: /data
                readOnly: false
                storageClass: ""
                volsync:
                    - credentials: ${S3_NAME}
                      dest:
                        enabled: true
                      name: data
                      src:
                        enabled: true
                      type: restic
        release_name: watchyourlan
        service:
            main:
                enabled: true
                type: ClusterIP
        watchyourlan:
            gui_ip: ${IP_TRUENAS}
            interfaces:
                - enp1s0
            shoutrrr_url: ""
            theme: darkly
            timeout: 300