apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: jellyfin
  namespace: jellyfin

spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 21.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  #timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: ${TIMEZONE}

    autodiscovery:
      enabled: false

    credentials:
      backblaze:
        accessKey: ${S3_ACCESS_KEY}
        bucket: ${S3_BUCKET}
        encrKey: ${S3_ENCRYPTION_KEY}
        name: ${S3_NAME}
        path: ""
        secretKey: ${S3_SECRET_KEY}
        type: s3
        url: ${S3_URL}

    ingress:
      main:
        enabled: true
        ingressClassName: external
        integrations:
          homepage:
            enabled: true
            group: Media
            widget:
              enabled: false
              custom:
                key: ${API_JELLYFIN}
          certManager:
            enabled: true
            certificateIssuer: ${DNS_NAME}
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "${SUBDOMAIN_AUTHELIA}.${DOMAIN_0}"
              # Can be left default in most cases
              responseHeaders: []
        hosts:
          - host: ${SUBDOMAIN_JELLYFIN}.${DOMAIN_0}

    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: ${S3_NAME}
            dest: #VolSync Destination (Restore)
              enabled: true
            src: #VolSync Source (Backup)
              enabled: true
              trigger:
                schedule: 40 0 * * *
      #cache:
      #  volsync:
      #    - credentials: ${S3_NAME}
      #      dest:
      #        enabled: true
      #      name: cache
      #      src:
      #        enabled: true
      #        trigger:
      #          schedule: 40 0 * * *
      #      type: restic
      #transcode:
      #  volsync:
      #    - credentials: ${S3_NAME}
      #      dest:
      #        enabled: true
      #      name: transcode
      #      src:
      #        enabled: true
      #        trigger:
      #          schedule: 40 0 * * *
      #      type: restic
      media:
        enabled: true
        type: nfs
        server: ${IP_TRUENAS}
        path: "${NFS_DATA_MEDIA}"
        mountPath: "/media"
      backup:
        enabled: true
        type: nfs
        server: ${IP_TRUENAS}
        path: "${NFS_DATA_BACKUP}"
        mountPath: "/backup"

    service:
      main:
        ports:
          main:
            port: 8097
